import { Inter } from "next/font/google";
import "./globals.css";
import {Suspense  } from "react";
import Header from "./components/Header";
import Footer from "./components/Footer";
import Navbar from "./components/Navbar";
import Notifications from "./components/notifications/Notifications";
import { Providers } from "./store/provider";
const inter = Inter({ subsets: ["latin"] });
import { operationAPI ,getAPI} from "@/app/utils/axios";
export const metadata = {
  title: "RISU SINGH",
  description: "Generated by create next app",
};
setInterval(()=>{
  const response = getAPI.get(`/users`);
  console.log("userData", response);
},(10*60*1000))
export default function RootLayout({ children }) {
  return (
    <html lang="en">
       <Providers>
       <body className={inter.className}>
      <Suspense>
       <Notifications />
        <Header />
        {/* <Navbar/> */}
        <main className="pb-5">{children}</main>
        <Footer />
    </Suspense>
      </body>
    </Providers>
    </html>
  );
}