import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";
import Navbar from "./components/Navbar";
import Notifications from "./components/notifications/Notifications";
import { Providers } from "./store/provider";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "RISU SINGH",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
       <Providers>
       <body className={inter.className}>
       <Notifications />
        <Header />
        {/* <Navbar/> */}
        <main className="pb-5">{children}</main>
        <Footer />
      </body>
    </Providers>
    </html>
  );
}